
user: wjw_9396@163.com
password: SNXRORADDWSVDLMS
port: 'smtp.163.com'

recipient: wjw_9396@163.com
email_title: YOLOv5 training report
email_content: Please see the attachment file for more information

